name: bluefang
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.2.3+16 # Bluefang ap verion number

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_settings: ^4.1.8
  background_fetch: ^1.1.0
  bloc: ^8.1.0
  convert: ^3.0.1
  cupertino_icons: ^1.0.2
  custom_vin_decoder:
    path: ./lib/package/vin-decoder-dart
  dartz: 0.10.0-nullsafety.2
  equatable: ^2.0.3
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  firebase_performance: ^0.9.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_blue_plus: ^1.3.1
  flutter_dotenv: ^5.0.2
  flutter_email_sender: ^5.1.0
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.0.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.1.0
  freezed_annotation: null
  get_it: ^7.2.0
  http: ^0.13.5
  hydrated_bloc: ^9.0.0
  injectable: ^1.4.1
  instant: ^0.4.1
  intl: any
  json_annotation: ^4.4.0
  json_diff: ^0.2.0
  kt_dart: ^0.9.1
  lint: ^1.5.3
  location: ^4.3.0
  lottie: ^1.1.0
  matcher: ^0.12.10
  mobile_scanner: ^2.0.0
  path_provider: ^2.0.2
  permission_handler: ^10.0.0
  provider: ^6.0.1
  shared_preferences: ^2.0.13
  sqflite: ^2.1.0
  stats: ^2.0.0
  sticky_and_expandable_list: ^1.0.2
  url_launcher: ^6.1.4
  

dev_dependencies:
  #bloc_test: any
  build_runner: ^2.1.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.5
  injectable_generator: ^1.4.1
  integration_test:
    sdk: flutter
  json_serializable: null
  mockito: ^5.1.0
  sqflite_common_ffi: ^2.1.1

# dependency_overrides:
#   firebase_core_platform_interface: 4.5.1

flutter_native_splash:
  color: "#18628E"
  image: asset/images/splash.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/VehicleStockImages/
    - assets/images/
    - assets/images/MakeIcons/
    - assets/lottie/
    - assets/SQLLiteDb/
    - assets/
    - .env
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
